ARG BASE_IMAGE="ghcr.io/gbraad-devenv/almalinux-golang/dotfiles"
ARG BASE_VERSION="9"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/almalinux-golang"

USER root

RUN systemctl enable tailscaled

ENTRYPOINT ["/sbin/init"]
