ARG BASE_IMAGE="ghcr.io/gbraad-devenv/almalinux-golang/base"
ARG BASE_VERSION="9"

FROM ${BASE_IMAGE}:${BASE_VERSION}

LABEL org.opencontainers.image.source = "https://github.com/gbraad-devenv/almalinux-golang"

USER gbraad

ENTRYPOINT [ "/bin/zsh" ]